yearn/yearn-vaults-v3

README.md
contracts/test/Token.sol
requirements-dev.txt
tests/conftest.py
tests/e2e/test_deposit_withdraw_flow.py
tests/unit/vault/test_shares.py
tests/utils/actions.py

- bumped ape to 0.3
- fixed test errors (0.3 checks types more rigorously in function calls)
- fixed install instructions to use `ape install plugins .`

chore: bump ape to 0.3, fix errors + install instructions

---

contracts/VaultV3.vy
tests/conftest.py
tests/e2e/test_strategy_withdraw_flow.py
tests/unit/vault/test_shares.py
tests/unit/vault/test_strategy_withdraw.py
tests/utils/actions.py

Implement the ability to withdraw from strategies. Withdrawing from lossy strategies not handled yet (as it requires the losses to be reported).
Added e2e test for withdrawing from strategies. 
Close #33

feat: implement withdraw from strategies

---

tests/unit/vault/test_vault_accounting.py

@anticlimactic I had a quick look but haven't seen a test to make sure the PPS doesn't increase on aidrop.

test: add pps not increase test

---

contracts/VaultV3.vy
tests/unit/vault/test_debt_management.py

added variable `minimumTotalIdle` to ensure a minimum liquidity is always available in the Vault
Fixes #44

feat: minimumTotalIdle

---

contracts/VaultV3.vy
contracts/periphery/FlexibleFeeManager.vy
tests/conftest.py
tests/unit/vault/test_strategy_profit_distribution.py

By subtracting fees from profit being locked, we were actually locking the fees for ever. Fees should not be reduced from profit, as they are being paid with dilution by issuing yvTokens
Fixes #64  (fix)

fix: ensured profits with fees are correctly considered

---

contracts/VaultFactory.vy
tests/unit/factory/test_ownership.py

Changes:
Allow for the governance of the Factory to be able to be changed. 
Reasoning:
1. Otherwise it would have to be deployed by the ychad multisig every time there is a new Vault version wanting to be released.
3. Ideally in the future ownership over the fees should be given to a contract veYFI holders control, but if Gov is not transferrable for the older versions it would never be able to direct the fees for all older vaults.
2. This factory should deploy every vault and last forever. Meaning if at any time the owner was compromised or then fees for every vault ever deployed using this factory can now be siphoned off to a incorrect address.
see https://github.com/flashfish0x/yearn-vaults-v3/pull/4

build: allow the factory gov to transfer

---

contracts/BaseStrategy.sol
contracts/VaultV3.vy
tests/unit/vault/test_profit_unlocking.py
tests/unit/vault/test_role_permissioned_access.py
tests/unit/vault/test_sweep.py

why: Its' unused
why: Move it with the other constant variables
Should the api's be changed to use 3? i.e. 3.1.0
why: the function is only called during the report and does not need the return variable
why: This function is only ever called during a report which will update the needed profit unlock variables at the end of the report. If all shares are unlocked then they are all burned, balanceOf(self) == 0 and therefore will not effect any calculations between the burning of shares and the end of the report
why: Adding a min check after a withdraw will assure that we will never underflow on the subtraction from total_debt and the strategies debt even if the strategy incorrectly sends even 1 wei extra tokens when moving debt to 0.
While the 4626 standard should prevent this from happening. …

fix: tweaks

---

README.md
contracts/VaultV3.vy
contracts/test/mocks/ERC4626/BaseStrategyMock.sol
contracts/test/mocks/ERC4626/FaultyStrategy.sol
contracts/test/mocks/ERC4626/LockedStrategy.sol
contracts/test/mocks/ERC4626/LossyStrategy.sol
tests/unit/vault/test_debt_management.py
tests/unit/vault/test_strategy_withdraw.py

Use redeem instead of withdraw on debt updates so we can natively take on losses.
#174

fix: debt withdraw

---

contracts/VaultV3.vy
tests/unit/vault/test_erc4626.py
tests/unit/vault/test_role_base_access.py
tests/unit/vault/test_role_permissioned_access.py
tests/unit/vault/test_strategy_withdraw.py

Let governance override custom withdraw queues

build: override queue

---

TECH_SPEC.md
contracts/VaultV3.vy
tests/unit/vault/test_debt_management.py

- Add an optional parameter to debt updates of 'max_loss' that works just like the redeem function.
- defaults to 100%

feat: add debt max loss

---

contracts/VaultV3.vy
contracts/test/mocks/ERC4626/MockTokenizedStrategy.sol

Most reports will burn shares twice and mint once causing unnecesary gas usage.
This will calculate the end state of shares first and then only burn OR mint depending on the amount needed to change.

build: only burn or mint

---

.github/workflows/test.yaml
contracts/VaultFactory.vy
contracts/VaultV3.vy
contracts/interfaces/IVault.sol
contracts/interfaces/IVaultFactory.sol
contracts/interfaces/Roles.sol
contracts/interfaces/VaultConstants.sol
contracts/test/mocks/ERC4626/MockTokenizedStrategy.sol
scripts/deploy.py
tests/conftest.py
tests/unit/factory/test_factory.py
tests/unit/vault/test_shares.py

Switch from using blueprints to cloning for lower deployment costs.

feat: use cloning for vaults

---

contracts/VaultV3.vy
tests/unit/vault/test_queue_management.py

Add an optiona `add_to_queue` flag on the add_strategy function that can allow the strategy to not automatically be added to the default_queue when added to the vualt.

feat: add to queue flag

---

ape-config.yaml
contracts/VaultV3.vy
contracts/test/ERC4626BaseStrategy.sol
contracts/test/mocks/ERC4626/MockTokenizedStrategy.sol
package.json
tests/unit/vault/test_strategy_withdraw.py

- Check for 0 assets
- Don't cache unnecessary variables in redeem
- dont burn shares if there are none
- clarify variable name in unrealized loss assesment
- bump oz version up 
- Use convertToShares instead of previewWithdraw in maxRedeem.
This will round down instead of up. Eliminating a potential issue caused by double rounding in which the convertToAssets in redeem will return a value slightly higher than the max_withdraw

feat: minor fixes

---

contracts/VaultV3.vy
contracts/test/mocks/ERC4626/MockTokenizedStrategy.sol
tests/unit/vault/test_profit_unlocking.py

- Lower gas cost of reports
- Only mint or burn once based on ending state
- remove multiple converTo calls.
- Only adjust the fees for the report if we need to.
- set unlock date to 0 instead of unlock rate for cheaper totalSupply() calls
- only updates lastReport once.

fix: reporting costs

---

.github/workflows/foundry.yaml
.github/workflows/lint.yaml
.gitmodules
contracts/VaultV3.vy
foundry.toml
foundry_tests/tests/ERC4626Std.t.sol
tests/unit/vault/test_erc4626.py

Give special flow for if max uint256 is passed on deposit call to pull 100% of the senders asset.

build: allow max uint

---

TECH_SPEC.md
contracts/VaultV3.vy
tests/unit/vault/test_role_base_access.py

- Allow Role Manager to update the name and the symbol
- Does not emit an event
- Should we change the `salt` the factory uses to not use name and symbol now?

feat: update name and symbol

---

contracts/VaultV3.vy

Pass the current debt of the strategy as a parameter into `_assess_share_of_unrealised_losses` to avoid needing to pull from storage again within the function

feat: pass debt to asses unrealised loss

---

.github/workflows/test.yaml
contracts/VaultV3.vy
tests/unit/vault/test_vault_accounting.py

Allow for a report to be processed with the vaults address sent to `process_report` that will account for any loose asset airdropped to the vault

feat: report on self

---

.github/workflows/lint.yaml
TECH_SPEC.md
contracts/VaultV3.vy
tests/unit/vault/test_auto_allocate.py
tests/unit/vault/test_debt_management.py

- Add an `auto_allocate` flag to the be set by the DEBT_MANAGER to automatically push all available debt to the first strategy in the queue during every deposit and mint

build: auto allocate

---

contracts/VaultFactory.vy
tests/unit/factory/test_protocol_fees_config.py
tests/unit/vault/test_protocol_fees.py

Pack and unpack PF config into one slot manually since vyper does not support storage packing to save an sload in all scenarios.
- Save 1810 gas during the normal operation.

feat: pack pf config

---

.gitmodules
ape-config.yaml
contracts/interfaces/IVaultFactory.sol

update IVaultFactory interface and use just released Tokenized Strategy version 3.0.3

chore: fix interface and version

---

contracts/VaultV3.vy
foundry_tests/handlers/VaultHandler.sol
package.json
tests/unit/vault/test_emergency_shutdown.py
tests/unit/vault/test_roles.py
tests/unit/vault/test_strategy_accounting.py
yarn.lock

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

fix: chainsec audit fixes
